enable_debug: true
env: local
app:
  name: service-template-go
  port: 8080
mysql:
  host: localhost
  port: 3306
  user: root
  password: 123456
  dbname: service_template_go
redis:
  host: localhost
  port: 6379
  password: 123456
